### ISSUE TITLE
Test Auto Shot Mechanics

### ISSUE THREAD

**Issue by BradBlondebeard** [watchyoursixx/hunter-wotlk-classic#16]
Does Auto Shot have a cast time?
Does the retry timer still exist?

**Comment by watchyoursixx** [comment]
Auto shot does not have a "cast time" but it does have a "start time" where pressing it takes about 0.15 sec before it actually starts.

The retry timer lives on, but only really affects movement because otherwise auto casts through everything.

Waiting to see if this changes with a fix to auto casting through everything or not.

**Comment by watchyoursixx** [comment]
steady shot is fixed and no change, so im gonna say this is finalized barring any future changes. Retry is here to stay at least for now.
